https://developer.mbed.org/handbook/USBSerial
https://developer.mbed.org/users/veskokaradzhov/code/AnalogSensorsLogging/file/c4cf65fb17fb/main.cpp
https://github.com/processing/processing-android/wiki
http://www.element14.com/community/community/designcenter/technical_library/content?filterID=contentstatus%5Bpublished%5D~category%5Btraining-video%5D&start=20
https://developer.mbed.org/users/MadVoltage/notebook/mbed-lpc1768-eagle-library/
http://www.icoconverter.com/
https://tiktakx.wordpress.com/2010/11/21/serial-port-interfacing-with-vb-net-2010/
http://www.theengineeringprojects.com/2012/10/microsoft-visual-basic-2010-com-port-tutorial.html
http://www.dreamincode.net/forums/topic/266749-logging-data-ie-temperature-over-time-to-database-and-draw-graph/
http://www.vbtutor.net/vbtutor.html
http://www.dreamincode.net/forums/topic/40143-introduction-to-graphs-in-vbnet/
http://www.cplusplus.com/reference/cstdio/fseek/
http://www.instructables.com/id/Temperature-and-Humidity-on-a-Graphical-LCD/step2/Code/
http://www.industrybuying.com/soldering-station-siron-SO.SO39.493554/?utm_source=Google&utm_medium=PLA&utm_campaign=0_PLA_HPP&gclid=CjwKEAiAluG1BRDrvsqCtYWk81gSJACZ2BCeb469dgcG5gLKDmg4P_4fpa-4QDdHdR9B4xKejRIRphoCDXzw_wcB
http://www.snapdeal.com/product/quick-858d-digital-smd-rework/621244027661?utm_source=earth_feed&utm_campaign=5_93&utm_medium=109388403&vendorCode=S2a2d1
http://www.industrybuying.com/soldering-station-soldron-SO.SO39.452245/?utm_source=Google&utm_medium=PLA&utm_campaign=0_PLA_HPP&gclid=CjwKEAiAluG1BRDrvsqCtYWk81gSJACZ2BCe2xHamOSfHyZ1XP_y-AuAmkOFntHOt3cmfLyX4ZtEWBoCxDfw_wcB
http://www.ebay.com/itm/PT100-PT1000-temperature-converter-SPI-digital-output-Arduino-MAX31865-from-EU-/171701993176
http://examples.digi.com/get-started/basic-xbee-zb-zigbee-chat/6/
http://www.sunrom.com/p/finger-print-sensor-r305
http://www.ebay.in/itm/5x-piece-USB-Type-B-Female-Connector-Sockets-PCB-Mount-/141877400079?hash=item21088d520f:g:~CsAAOSwZG9Wl9GI
http://www.amazon.in/gp/product/B00I6L4MOK/ref=s9_simh_gw_p147_d5_i1?pf_rd_m=A1VBAL9TL5WCBF&pf_rd_s=desktop-top&pf_rd_r=0V4C9HN0VAJPHYB4RDVR&pf_rd_t=36701&pf_rd_p=821056287&pf_rd_i=desktop
http://www.amazon.in/uxcell%C3%82%C2%AE-Surface-Push-out-Memory-Socket/dp/B00E6PVMU2/ref=sr_1_6?s=computers&ie=UTF8&qid=1459163485&sr=1-6&keywords=microSD+card+socket
https://www.arrow.com/en/products/search?q=LMT89DCKR&filters=Manufacturer_name:Texas+Instruments
https://openenergymonitor.org/emon/buildingblocks/rtd-temperature-sensing
http://www.ebay.in/sch/i.html?_from=R40&_trksid=p2047675.m570.l1311.R1.TR4.TRC0.A0.H0.X200+ohm.TRS0&_nkw=200+ohm+potentiometer&_sacat=0
http://esd.cs.ucr.edu/labs/tutorial/adder.vhd
deepu-diyprojects.blogspot.in
http://www.microchip.com/wwwproducts/en/PIC32MX440F256H
http://www.microchip.com/wwwproducts/en/PIC32MX440F256H
http://wiki.pinguino.cc/index.php/MPLAB_X_and_Pinguino_PIC32_DIY
https://www.youtube.com/watch?v=lQ6YKQt6Rz4
http://www.xilinx.com/products/boards/s3estarter/reference_designs.htm
https://therobotfix.wordpress.com/2011/06/27/getting-started-with-spartan-3e-fpga-and-verilog/
https://hackaday.io/project/4977-portable-environmental-monitor
https://github.com/wgwozdz
http://processors.wiki.ti.com/index.php/Getting_Started_with_the_TIVA%E2%84%A2_C_Series_TM4C123G_LaunchPad
https://m.ebay.in/itm?itemId=252207421093
https://docs.mbed.com/docs/lora-with-mbed/en/latest/intro-to-lora/#conclusion
https://docs.mbed.com/docs/lora-with-mbed/en/latest/intro-to-lora/
http://www.adslwi-fi.com/aa.php?isbn=ISBN:8186340610&name=Question_Bank_In_Electronics_And_Communication_Engineering
http://shukra.cedt.iisc.ernet.in/edwiki/EdWiki
http://www.sitelinks.info/search/semtech-sx1278/
http://www.ebay.in/itm/152133837021?aff_source=Sok-Goog
http://www.technobuzz.net/android-6-0-marshmallow-ota-micromax-canvas-a1/
http://docs.opencv.org/trunk/d3/d52/tutorial_windows_install.html#gsc.tab=0
http://www.citlprojects.com/embedded-projects/ieee-internet-things-iot
http://www.digikey.com/schemeit/project/
http://www.enevo.com/
https://schematics.io/
https://raw.githubusercontent.com/esp8266/Arduino/master/libraries/ESP8266WebServer/examples/SDWebServer/SDWebServer.ino
https://github.com/nodemcu/nodemcu-firmware/tree/master/app
https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WiFi
http://www.ocfreaks.com/lpc2148-pwm-programming-tutorial/
https://www.youtube.com/watch?v=L2jRiyRfHpk
https://www.youtube.com/watch?v=eJg3yuAAawA
https://www.youtube.com/watch?v=z9Cqm28lbRk
https://developer.mbed.org/users/SamClarke/code/GPS-GPRS_Tracker/file/5a33972c09e0/main.cpp
https://developer.mbed.org/teams/ESP8266/code/ESP8266_HTTP_HelloWorld/
https://api.thingspeak.com/update?api_key=F0UP0HAHF48TZ9PI&field1=50
http://www.labnol.org/internet/host-website-on-google-drive/28178/
https://msdn.microsoft.com/en-us/library/aa711083(v=vs.71).aspx
https://msdn.microsoft.com/en-us/library/7af2feyt(v=vs.90).aspx
http://vb.net-informations.com/excel-2007/vb.net_excel_2007_open_file.htm
https://msdn.microsoft.com/en-us/library/s2dy91zy.aspx
http://www.instructables.com/id/Water-meter-Arduino-Aquameterduino-/
https://github.com/TheThingsNetwork/workshops
http://www.chegg.com/my/expertqa
https://cart.ebay.in/sc/gadd?itemid=222312763087&quantity=1
http://www.ebay.in/itm/322307679162?rmvSB=true
http://www.electroschematics.com/12610/how-to-play-with-thermocouples/
http://www.shelfkey.com/orderProduct.aspx?prodid=9713&partno=1505-5PIN-5.08MM
http://cds.linear.com/image/32020.png
https://developer.mbed.org/questions/111/Stopping-the-operation-of-a-thread/
http://www.xcluma.com/development-boards?page=3
https://eth0maz.wordpress.com/2016/05/27/lorawan-iot-node/



